---
title: FleetBox
author: Hamza Imloul
email: hamzaonde@gmail.com
description: FleetBox is a service for fleet management, our support engineers will
  take your operations into insghts
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
